version: '3'

services:
  nginx-app:
    container_name: nginx-app
    image: nginx:alpine
    ports:
      - 8888:80
    volumes:
      - ./php-hello-world-main:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-app

  php-app:
    container_name: php-app
    build: .
    ports:
      - 8008:8000